#!/bin/sh
# /etc/pm/sleep.d/99asus_superhe_sleep
#
# http://idolinux.blogspot.com/2012/01/fedora-16-xfce-on-eee-pc.html
#
 
Ac="/sys/bus/acpi/drivers/ac/ACPI0003:00/power_supply/AC0/online"
 
case "$1" in
    thaw)
        if  [ -f $Ac ]; then
            if grep 0 "$Ac" > /dev/null; then
                /etc/pm/power.d/99asus_superhe_power true
            fi
        else
            /etc/pm/power.d/99asus_superhe_power false
        fi
esac
 
exit 0
