#!/bin/bash
# /etc/pm/power.d/99asus_superhe_power
#
# http://idolinux.blogspot.com/2012/01/fedora-16-xfce-on-eee-pc.html
#

CpuFv="/sys/devices/platform/eeepc/cpufv"

case "$1" in
    true)
        /bin/echo -n 2 > "$CpuFv"
    ;;
    false)
        /bin/echo -n 0 > "$CpuFv"
    ;;
esac

exit 0
