#!/bin/bash
# /etc/pm/power.d/99asus_superhe_power
#
# http://idolinux.blogspot.com/2012/01/fedora-16-xfce-on-eee-pc.html
#

CpuFv="/sys/devices/platform/eeepc/cpufv"
Backlight="/sys/class/backlight/eeepc/brightness"

case "$1" in
	true)
		if  [ -f $CpuFv ] && [ -f $Backlight ]; then
			/bin/echo -n 2 > "$CpuFv"
			/bin/echo -n 2 > "$Backlight"
		else
			exit 14
		fi
    ;;
	false)
		if  [ -f $CpuFv ] && [ -f $Backlight ]; then
			/bin/echo -n 0 > "$CpuFv"
			/bin/echo -n 10 > "$Backlight"
		else
			exit 14
		fi
    ;;
esac

exit 0
